services:
  # Container - MySQL
  db:
    image: mysql:8.0
    container_name: almox-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: almoxarifado
      MYSQL_ROOT_PASSWORD: "mysql_root"
    ports:
      - "3306:3306"
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql


  # Container - app.py
  site_web:
    build: .
    container_name: almox-site
    ports:
      - "5000:5000"
    command: python app.py
    depends_on:
      - db




